# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_cost', models.IntegerField()),
                ('recognised_revenue_otd', models.IntegerField()),
                ('invoice_revenue_otd', models.IntegerField()),
                ('actual_cost_otd', models.IntegerField()),
                ('recognised_revenue_ytd', models.IntegerField()),
                ('invoice_revenue_ytd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_backlog', models.IntegerField()),
                ('cost_to_go', models.IntegerField()),
                ('backlog_margin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in', models.IntegerField()),
                ('excess_billing', models.IntegerField()),
                ('overdue', models.IntegerField()),
                ('c_minus_i', models.IntegerField()),
                ('c_minus_r', models.IntegerField()),
                ('c_minus_r_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=255)),
                ('prj_number', models.CharField(max_length=255)),
                ('prj_manager', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_sold_revenue', models.IntegerField()),
                ('as_sold_cost', models.IntegerField()),
                ('as_sold_margin_cost', models.IntegerField()),
                ('ps1_margin_lgm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PS4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_sold_revenue', models.IntegerField()),
                ('as_sold_cost', models.IntegerField()),
                ('as_sold_margin_cost', models.IntegerField()),
                ('ps4_margin_lgm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_centre', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('app_centre', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='client',
        ),
    ]
