# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0002_auto_20160906_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='backlog_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='cost_to_go',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='revenue_backlog',
            field=models.FloatField(),
        ),
    ]
