# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0005_auto_20160914_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM', models.CharField(max_length=255)),
                ('Prj_nos', models.IntegerField()),
                ('PS1', models.FloatField()),
                ('PS4', models.FloatField()),
                ('PS1vsPS4', models.FloatField()),
                ('Q1', models.FloatField()),
                ('Q2', models.FloatField()),
                ('Q3', models.FloatField()),
                ('Q4', models.FloatField()),
                ('cr', models.FloatField()),
                ('crp', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actuals',
        ),
        migrations.DeleteModel(
            name='Backlog',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Pinfo',
        ),
        migrations.DeleteModel(
            name='PS1',
        ),
        migrations.DeleteModel(
            name='PS4',
        ),
        migrations.DeleteModel(
            name='Reporting',
        ),
    ]
