# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0006_auto_20160925_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='Prj_nos',
            new_name='P_nos',
        ),
    ]
