# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0007_auto_20160925_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='db1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('wbsElement', models.CharField(max_length=255)),
                ('wbsName', models.CharField(max_length=255)),
                ('act', models.CharField(max_length=255)),
                ('cusNo', models.FloatField()),
                ('cusName', models.CharField(max_length=255)),
                ('cosType', models.CharField(max_length=255)),
                ('cosElementName', models.CharField(max_length=255)),
                ('ps0', models.FloatField()),
                ('ps2', models.FloatField()),
                ('ps4', models.FloatField()),
                ('actual', models.FloatField()),
                ('commitment', models.FloatField()),
                ('poc', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
