# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0009_auto_20161025_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='db1',
            name='cosElementNumber',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
