# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0011_auto_20161101_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('pdiff', models.FloatField()),
                ('ndiff', models.FloatField()),
                ('base', models.FloatField()),
                ('end', models.FloatField()),
                ('cosElementName', models.CharField(max_length=255)),
            ],
        ),
    ]
