# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0013_auto_20161102_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='base',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='cosElementName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='curr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='fin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='nDiff',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='pDiff',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='start',
            field=models.FloatField(null=True),
        ),
    ]
