# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csViewer', '0015_auto_20161103_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='lag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='curr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='nDiff',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='pDiff',
            field=models.FloatField(null=True),
        ),
    ]
